networks:
  pgadmin:
    external: true

services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "44556:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: default@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - pgadmin
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
